name: Cron Todo List

on:
  # 매일 30분마다.
  schedule:
    - cron: "*/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: run application
        run: npm start
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
