name: Cron Todo List

on:
  # 매일 8~22시 사이 10분마다.
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Npm Install
        run: npm install
      - name: Run Application
        run: npm start
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
